CREATE TABLE IF NOT EXISTS venues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    capacity integer NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    venue_id bigint REFERENCES venues(id),
    start_time timestamp NOT NULL,
    price_per_seat numeric NOT NULL DEFAULT 0,
    booked_seats integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES events(id),
    customer_name varchar(255) NOT NULL,
    seat_count integer NOT NULL,
    status varchar(20) NOT NULL
);
