spring.application.name=ticketing
booking.max-seats-per-booking=8

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

spring.docker.compose.file=compose/docker-compose.yml
