CREATE TABLE IF NOT EXISTS venues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    capacity integer NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    venue_id bigint REFERENCES venues(id),
    start_time timestamp NOT NULL,
    booked_seats integer NOT NULL DEFAULT 0
);
