[versions]
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
testcontainers = "2.0.5"
spring-modulith = "2.1.1"
archunit = "1.5.1"
resilience4j = "2.4.0"
google-cloud-libraries-bom = "26.86.0"
google-cloud-sql-postgres-socket-factory = "1.30.0"

[libraries]
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-mongodb = { module = "org.testcontainers:testcontainers-mongodb", version.ref = "testcontainers" }
testcontainers-rabbitmq = { module = "org.testcontainers:testcontainers-rabbitmq", version.ref = "testcontainers" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core", version.ref = "spring-modulith" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test", version.ref = "spring-modulith" }
spring-modulith-docs = { module = "org.springframework.modulith:spring-modulith-docs", version.ref = "spring-modulith" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
resilience4j-spring-boot4 = { module = "io.github.resilience4j:resilience4j-spring-boot4", version.ref = "resilience4j" }
spring-boot-core = { module = "org.springframework.boot:spring-boot", version.ref = "spring-boot" }
google-cloud-libraries-bom = { module = "com.google.cloud:libraries-bom", version.ref = "google-cloud-libraries-bom" }
google-cloud-secretmanager = { module = "com.google.cloud:google-cloud-secretmanager" }
google-cloud-sql-postgres-socket-factory = { module = "com.google.cloud.sql:postgres-socket-factory", version.ref = "google-cloud-sql-postgres-socket-factory" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
